M48
; DRILL file {KiCad 9.0.0} date 2025-04-29T18:34:19-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-29T18:34:19-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X163.02Y-82.61
X163.02Y-88.39
T2
X167.0Y-94.25
X167.0Y-97.25
T3
X128.5Y-52.0
X128.5Y-127.0
X165.5Y-52.0
X165.5Y-127.0
M30
